; This file was automatically generated by ScriptHubImporter.py
<<<<<<< Updated upstream
global g_ImportsGameVersion64 := 554
=======
global g_ImportsGameVersion64 := 555
>>>>>>> Stashed changes
global g_ImportsGameVersionPostFix64 := ""